### ISSUE TITLE
Problem with Resize CMYK  image

### ISSUE THREAD

**Issue by BedunkevichE** [coobird/thumbnailator#100]
Hi, also will  open new issue cause same   old issue is closed without any  working solution
have the error when  try to resize the CMYK image

Thumbnails.of(sourceFile).outputQuality(0.6).size(528, 528).outputFormat("jpg").toFile(thumbnail);

javax.imageio.IIOException: Unsupported Image Type
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1068)
    at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
    at net.coobird.thumbnailator.tasks.io.FileImageSource.read(Unknown Source)
    at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(Unknown Source)
    at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Unknown Source)

the target image is attached

![channel_digital_image_cmyk_color](https://cloud.githubusercontent.com/assets/18334690/17964148/5eb7c128-6ac1-11e6-9df4-98abc9838d78.jpg)

thanks for help.

**Comment by BedunkevichE** [comment]
think it is a problem ImageIO.read(sourceFile).....
any way to solve it via Thumbnails?

**Comment by BedunkevichE** [comment]
the problem is solved via this link
http://www.randelshofer.ch/blog/2011/08/reading-cmyk-jpeg-images-with-java-imageio/
and this class
http://www.randelshofer.ch/monte/javadoc/org/monte/media/jpeg/CMYKJPEGImageReader.html

**Comment by coobird** [comment]
Thank you for filing this issue, and apologies for not responding in a timely fashion.

Basically, Thumbnailator is only a wrapper around the Java Image I/O API, therefore, if the image readers and writers that are loaded into the Image I/O API does not support the input format, you will encounter problems that you've seen.

In your case, it appears that you found the resolution by using a third-party `ImageReader` that supports CMYK JPEGs by registering that codec into Image I/O -- this is the best approach to take if the codecs bundled with the JRE are insufficient.

Since the scope of the Thumbnailator project does not include providing the image codecs, I'll be closing this issue.

Once again, thank you for taking time to report this issue.
