### ISSUE TITLE
Using thumbnailator as a tool for general purpose resizing

### ISSUE THREAD

**Issue by akshaysmurthy** [coobird/thumbnailator#110]
Is there any reason not to use thumbnailator to resize an image to a size which is *not necessarily a thumbnail*.

My specific use case is something like this:

I have **4000 x 2000** images which I want to resize to **2000 x 1000**.

Thanks

**Comment by coobird** [comment]
If your use case is to _downscale_ images, then Thumbnailator would probably work. (See _Note_ below.) It does try to take into account speed and quality consideration when _downscaling_ images, so Thumbnailator can be used for cases where one is not necessarily making thumbnails.

However, Thumbnailator does not really put much thought into _upscaling_ images. Quality, speed and memory usage considerations are not taken for enlarging images.

Therefore, it would be a stretch to say that Thumbnailator could be a _general purpose image resizing tool_, because in reality, it only concentrates on the use case of _downscaling_ images.

_Note:_ One additional point to make; downscaling large images to still large images will use quite a bit of memory while processing. Therefore, some attention would be needed in allocating an appropriate amount of heap space when starting the JVM. This really will depend on your workload, so I can't make any concrete recommendations about this.

**Comment by akshaysmurthy** [comment]
@coobird Thanks for the swift response. 

Understandable. Like I said, my use case is really downscaling larger images to 2000px wide images. I am guessing that's exactly what you referred to as *downscaling large images to still large images*. Is that correct?

**Comment by coobird** [comment]
@akshaysmurthy, yes, I would consider 2000 px wide images being "large images", at least when compared to typical thumbnail sizes that Thumbnailator was originally developed for. :)

**Comment by akshaysmurthy** [comment]
@coobird Thanks a lot :)
One final question. 
_downscaling large images to still large images will use quite a bit of memory while processing_ - That limitation isn't specific to Thumbnailator, right?

**Comment by coobird** [comment]
@akshaysmurthy, sorry for the delay in responding.

In general yes, handling large images would take quite a bit of memory usage, so it's not an issue that Thumbnailator would face. However, there are some ways to attempt to reduce memory usage (such as mentioned in Issue #1), but it's not something that's implemented yet in Thumbnailator.

**Comment by akshaysmurthy** [comment]
Thanks @coobird. That was very helpful :)

I'm closing this issue.
