### ISSUE TITLE
useExifOrientation flag is not respected for BufferedImage

### ISSUE THREAD

**Issue by KamilKrol** [coobird/thumbnailator#136]
## Expected behavior
When setting `useExifOrientation` flag to `true`, one can expect that Image orientation is handled properly no matter what Image source we use (InputStream, BufferedImage etc.).

## Actual behavior
Image orientation from EXIF metadata is respected in other cases.
After checking the source code it seems that:
- **BufferedImage - NOK**
- FileImageSource - OK
- InputStreamImageSource - OK
- URLImageSource - OK

## Steps to reproduce the behavior
Test cases reproducing the issue: https://github.com/KamilKrol/thumbnailator/commit/d839bb977c2102637db121ce5401d077c7689266
For the moment we have implemented workaround in our application, but we need to implement proper solution - ideally by providing Pull request to this library.

## Environment
Should be reproducible on any environment (implementation problem).
- OS vendor and version: Windows, Linux, MacOS
- JDK vendor and version: Oracle, OpenJDK
- Thumbnailator version: 0.4.8

**Comment by coobird** [comment]
[Exif](https://en.wikipedia.org/wiki/Exif) is metadata contained in image streams that support including Exif metadata. A [`BufferedImage`](https://docs.oracle.com/javase/8/docs/api/java/awt/image/BufferedImage.html) is an Java class which is essentially a buffer containing image data. `BufferedImage` is not a image format but rather a container for handling image data in Java, and does not include Exif metadata.

Since `BufferedImage` does not include Exif data, it is not possible to use it to determine orientation of a `BufferedImage` since it doesn't exist. Basically, the moment you [read the image stream to a `BufferedImage`](https://github.com/KamilKrol/thumbnailator/commit/d839bb977c2102637db121ce5401d077c7689266#diff-70dae98bdb805078b0b44c446dc51738R214) the Exif metadata is lost. Therefore, this behavior is expected.
