### ISSUE TITLE
Any plan to support converting webp?

### ISSUE THREAD

**Issue by majintao** [coobird/thumbnailator#137]
## Expected behavior
_Please describe what you are expecting the library to perform._

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version:
- JDK vendor and version:
- Thumbnailator version:

**Comment by chickFish** [comment]
good question

**Comment by Emmenemoi** [comment]
https://bitbucket.org/luciad/webp-imageio/src/default/
or its fork for easy maven build:
https://github.com/nintha/webp-imageio-core

**Comment by sunnynguyen-ai** [comment]
It'd be great if we can Thumbnails....outputFormat("webp")

**Comment by romulodiniz** [comment]
I hate spam, but any news on this support? thumbnailator is working great until now, but this lack of support for webp is a bit sad.

**Comment by nitelite** [comment]
The latest release of this lib was in like 2014 :P

**Comment by romulodiniz** [comment]
Yeah... I gave up a while ago :) Thanks!

**Comment by coobird** [comment]
Thumbnailator relies on the Java Image I/O API for reading and writing images; Thumbnailator itself doesn't include explicit support for any image file formats. Since out-of-the-box Java does not include support for WebP, If you want to support additional formats, you'll need to use Image I/O plugins that support the image format you want to use.

For example, check out the response from Emmenemoi (https://github.com/coobird/thumbnailator/issues/137#issuecomment-462295798) which includes a link to WebP support for Image I/O. Not sure how well it works since I haven't tried myself, but you'll need to look for external Image I/O plugins. (Looks like the fork on Github would be easy to use, if you have Maven, since all you'd have to do is include it as a runtime dependency.)

So, the answer is no, there will not be native support to Thumbnailator for WebP, but I think it would be worth including more information in the FAQ about this.
