### ISSUE TITLE
Can thumbnailator support HEIC images?

### ISSUE THREAD

**Issue by yeluowuhen52** [coobird/thumbnailator#160]
## Expected behavior
_Please describe what you are expecting the library to perform._
Support HEIC Images.

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._
I want to convert HEIC to JPG. 
No suitable ImageReader found for D:\IMG_20200925_191853.HEIC.

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._

  Thumbnails.of(new File("D:/IMG_20200925_191853.HEIC"))
                    .imageType(BufferedImage.TYPE_INT_RGB).scale(1).rotate(0).outputFormat("JPG")
                    .toFile(new File("expect.jpg"));

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version:Windows 10
- JDK vendor and version:8
- Thumbnailator version:0.4.12

**Comment by coobird** [comment]
Thumbnailator depends on the [Java Image I/O API](http://docs.oracle.com/javase/7/docs/technotes/guides/imageio/) to read and write images. Since Java does not come bundled with a HEIC image reader, you'll need to find a Image I/O API compatible image reader that supports HEIC.

A quick search did not yield any results for an Image I/O HEIC reading plugin, so you'll need to rely on another solution to convert the HEIC images to one supported by default in Java (such as PNG or JPEG) before using Thumbnailator.

**Comment by yeluowuhen52** [comment]
> Thumbnailator depends on the [Java Image I/O API](http://docs.oracle.com/javase/7/docs/technotes/guides/imageio/) to read and write images. Since Java does not come bundled with a HEIC image reader, you'll need to find a Image I/O API compatible image reader that supports HEIC.
> 
> A quick search did not yield any results for an Image I/O HEIC reading plugin, so you'll need to rely on another solution to convert the HEIC images to one supported by default in Java (such as PNG or JPEG) before using Thumbnailator.

Thanks for your reply.Android have the class 'android.graphics.ImageDecoder' whitch can convert HEIF pictures to JPG pictures.
