### ISSUE TITLE
No suitable ImageReader found

### ISSUE THREAD

**Issue by sunweihxh** [coobird/thumbnailator#163]
## Expected behavior
got a exception:net.coobird.thumbnailator.tasks.UnsupportedFormatException: No suitable ImageReader found

## Steps to reproduce the behavior
scale0_3 = new File(imagePath+File.separator+"scale0_3");
		
		scale0_6 = new File(imagePath+File.separator+"scale0_6");
		
		//Thumbnails.of(original).scale(0.3).toFile(scale0_3);
		//Thumbnails.of(original).scale(0.6).toFile(scale0_6);
		
		Thumbnails.of(original).scale(0.3).toOutputStream(new FileOutputStream(scale0_3));
		Thumbnails.of(original).scale(0.6).toOutputStream(new FileOutputStream(scale0_6));

## Environment
jdk1.8
tomcat8.5

- OS vendor and version:
- JDK vendor and version:
- Thumbnailator version:

**Comment by dmitry-weirdo** [comment]
Good day @sunweihxh!

You should post: 

- the image on which the exception occurred. 
- the full stacktrace of the exception.
- version of the thumbnailator used.


Most probably your image either has an unsupported format or is broken. AFAIR I had some exceptions on jpeg files that have broken EXIF info or something alike. I re-saved it with a graphic editor, after it the thumbnailator worked.
For HEIC files, I converted it to JPEG.

**Comment by sunweihxh** [comment]
### Thank you for your reminding. I used version 0.4.8. My error details are as follows：
net.coobird.thumbnailator.tasks.UnsupportedFormatException: No suitable ImageReader found for d:\images\image\courseUserWork\2020-10-15\xIVSkZlYEeGYhpNuokqG\original.
	at net.coobird.thumbnailator.tasks.io.FileImageSource.read(FileImageSource.java:118)
	at net.coobird.thumbnailator.tasks.SourceSinkThumbnailTask.read(SourceSinkThumbnailTask.java:76)
	at net.coobird.thumbnailator.Thumbnailator.createThumbnail(Thumbnailator.java:53)
	at net.coobird.thumbnailator.Thumbnails$Builder.toOutputStream(Thumbnails.java:2737)

### The picture I uploaded is
![original1](https://user-images.githubusercontent.com/20678453/96062662-cf5a9400-0ec8-11eb-8a72-b0502bad572c.jpg)

**Comment by coobird** [comment]
@sunweihxh The file you uploaded is a WebP image. (Despite the "jpg" extension it wasn't a JPEG.)

Thumbnailator relies on the Java Image I/O API's image reading and writing facilities, which does not have support for WebP out-of-the-box. In order to use WebP, you'll need to find a compatible Image I/O plugin.

There appears to be some options for using WebP from Java Image I/O which you'll be able to find in a previously filed issue (#137) and in a comment I made [here](https://github.com/coobird/thumbnailator/issues/137#issuecomment-578464544).

Once such a plugin is enabled, you should be able to use Thumbnailator without further modifications.

**Comment by sunweihxh** [comment]
@coobird @dmitry-weirdo thanks a lot.
