### ISSUE TITLE
The image becomes larger after compression

### ISSUE THREAD

**Issue by goooong** [coobird/thumbnailator#171]
code:
File file = new File("bailu.jpg");
Thumbnails.of(file).outputQuality(0.9d).scale(1d).toFile("bailu2.jpg");

before size :73kb
after size :76kb

**Comment by goooong** [comment]
before:
![bailu](https://user-images.githubusercontent.com/44569285/108662209-cded4800-7508-11eb-9468-7cf686e36e8c.jpg)
after:
![bailu2](https://user-images.githubusercontent.com/44569285/108662234-dd6c9100-7508-11eb-8af6-e786a8c53c95.jpg)

**Comment by coobird** [comment]
File sizes increasing for the same size image is completely expected when using JPEG.

There can be a couple of reasons for this -- first, if the original JPEG is using a lower quality setting (i.e. lower compression quality) the resulting image can be a larger file size. Second reason, even if the original image and the resulting image both were using the same quality setting, saving a JPEG again as a JPEG can lead to lower compression ratios, hence larger file sizes. And the resulting image will be likely less visual quality than the original. These two effects are due to the nature of JPEG compression.

This is not an issue with Thumbnailator, but a general nature of using JPEG image compression.

**Comment by goooong** [comment]
> File sizes increasing for the same size image is completely expected when using JPEG.
> 
> There can be a couple of reasons for this -- first, if the original JPEG is using a lower quality setting (i.e. lower compression quality) the resulting image can be a larger file size. Second reason, even if the original image and the resulting image both were using the same quality setting, saving a JPEG again as a JPEG can lead to lower compression ratios, hence larger file sizes. And the resulting image will be likely less visual quality than the original. These two effects are due to the nature of JPEG compression.
> 
> This is not an issue with Thumbnailator, but a general nature of using JPEG image compression.

thank you.

**Comment by micMalloc** [comment]
@coobird  Hello, I'm Heesu.
I would like to ask if it is the same for PNG.
Thanks.

<Code>
Thumbnails.of(input).scale(1.0f).outputQuality(0.85f).toFile("/Users/we/Desktop/output.png");

Before size: 18122
After size: 279584

[input image]
![input](https://user-images.githubusercontent.com/22839766/131688686-54643d23-eefd-4956-ab26-9215a21f5fb9.png)

[output image]
![output](https://user-images.githubusercontent.com/22839766/131688753-efc1de97-8c2f-4957-af55-9681b1851806.png)
