### ISSUE TITLE
the compressed image is abnormal

### ISSUE THREAD

**Issue by Herewell** [coobird/thumbnailator#191]
hi,
I found a problem as follows:
When I use the code below to compress the image，The compressed image is abnormal。
```
        Thumbnails.of(file)
                .size(640, 640)
                .keepAspectRatio(false)
                .toFile(resizeFile);
```
You can find the images before and after compression in the attachment。
How should i solve this problem，please help me 

Environment
JDK1.8 and thumbnailator's version is 0.4.8
after：
![after](https://user-images.githubusercontent.com/53120626/159882934-4a43e693-3997-476f-b171-9dc583eb4f83.jpg)
before:
![before](https://user-images.githubusercontent.com/53120626/159882981-7aaa547c-e1fd-4037-864e-a897f8f7b246.jpg)

**Comment by coobird** [comment]
This is a problem with Java's default JPEG reader not reading the JPEG properly.

You'll likely get better results if you use [TwelveMonkey ImageIO](https://github.com/haraldk/TwelveMonkeys)'s JPEG reader instead; you'll just need to [include it as a Maven dependency](https://github.com/haraldk/TwelveMonkeys#maven-dependency-example) and as long as it's in the classpath, that JPEG reader will be used instead of the default JPEG reader.

**Comment by Herewell** [comment]
it‘s ok,thanks!
