### ISSUE TITLE
SVG not supported

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coobird/thumbnailator#75]
```
I got this exception when I want to resize a SVG file : 

net.coobird.thumbnailator.tasks.UnsupportedFormatException: No suitable 
ImageReader found for source data.

```

Original issue reported on code.google.com by `maxime.m...@zenika.com` on 2 Apr 2015 at 1:02

**Comment by coobird** [comment]
Thumbnailator relies on the Java Image I/O API to handle input/output of image files.

As such, it is outside the scope of the Thumbnailator project to provide support for specific image formats.

That said, since Thumbnailator relies on the Image I/O API, if you use a library like TwelveMonkeys ImageIO (https://github.com/haraldk/TwelveMonkeys) which provides support for additional image formats, you should be able to use formats which are not supported by the stock Java distribution.

The TwelveMonkeys ImageIO library lists SVG as one of the supported input formats.
