### ISSUE TITLE
Transparency lost during image resize

### ISSUE THREAD

**Issue by jayabansal** [coobird/thumbnailator#93]
During image resizing, the transparency is lost and background becomes black.

**Comment by jayabansal** [comment]
![companion](https://cloud.githubusercontent.com/assets/19219641/15816892/d395b22e-2bf2-11e6-96bc-670571156863.png)
This is the original file of size 420 \* 280. I need to convert it into 200 \* 160 without loosing transparency. Please suggest

**Comment by coobird** [comment]
Thank you for taking the time to file this issue, and apologies for not responding in a timely fashion.

Since you haven't provided information regarding how you were trying to create the resized image, and what the actual result was, I'll assume you're using a code like the following:

```
Thumbnails.of("source.png")
    .size(200, 160)
    .toFile("destination.png")
```

If that's the case, in this instance, the original image uses a 8-bit palette with a transparent color, which Thumbnailator is creating a thumbnail with a 8-bit palette where the transparency is lost, hence the black background.

As a workaround, the following can be used to create a 24-bit w/ alpha channel image, which will preserve the transparency, and will give better looking results (albeit, the file size will be slightly larger)

```
Thumbnails.of("source.png")
    .size(200, 160)
    .imageType(BufferedImage.TYPE_INT_ARGB)
    .toFile("destination.png")
```

In any case, this issue happens to be an duplicate of an earlier issue (#41), so I will be closing this as an duplicate.

**Comment by godenji** [comment]
All it took was an "A" in `TYPE_INT_RGB`, awesome ;-)

Welcome back, btw, thank you for Thumbnailator!

**Comment by jtrommer** [comment]
thank you so mutch
Thumbnailator i a great library

**Comment by ghost** [comment]
good  !
